### ISSUE TITLE
Sayfa Hatası

### ISSUE THREAD

**Issue by detmach** [dotnet/AspNetCore.Docs.tr-tr#16]
[Geri bildiriminizi buraya girin]
Sayfa hatalı.

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: b6728e59-93ec-891e-0416-94819296ad72
* Version Independent ID: 5d581acc-c651-2112-844a-6b85dc5a99a6
* Content: [ASP.NET Core 'de yanıt önbelleğe almaResponse caching in ASP.NET Core](https://docs.microsoft.com/tr-tr/aspnet/core/performance/caching/response?view=aspnetcore-2.2)
* Content Source: [aspnetcore/performance/caching/response.md](https://github.com/dotnet/AspNetCore.Docs.tr-tr/blob/live/aspnetcore/performance/caching/response.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @detmach
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/AspNetCore.Docs #18614](https://github.com/dotnet/AspNetCore.Docs/issues/18614) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Merhaba @detmach,  

Katkılarınıza çok değer veriyoruz. Geri bildiriminiz orijinal belgelerle ilgili.  

Bu nedenle bu sorunu İngilizce deposuna geçiriyoruz. Lütfen sorunun durumunu buradan gözden geçirin - https://github.com/dotnet/AspNetCore.Docs/issues/18614.  

Makalelerimize yaptığınız katkılar bizim için çok değerlidir.   

Saygılarımla,  
Microsoft DOCS Uluslararası Ekibi
