### ISSUE TITLE
Iubcontext Must be IHubContext

### ISSUE THREAD

**Issue by yusufyilmazfr** [dotnet/AspNetCore.Docs.tr-tr#19]
It written wrong. Iubcontext must be IHubContext

---

* ID: 7bf6fefc-557e-114a-a37c-90939e06b083
* Version Independent ID: 92da23e0-6dc5-170e-b489-2ad8bbd46dff
* Content: [SignalR HubContext](https://docs.microsoft.com/tr-tr/aspnet/core/signalr/hubcontext?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/hubcontext.md](https://github.com/dotnet/AspNetCore.Docs.tr-tr/blob/live/aspnetcore/signalr/hubcontext.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
@Rick-Anderson this looks like a translation issue. can you help route? tia!

**Comment by yusufyilmazfr** [comment]
Hi @bradygaster, If you want I can contribute this page soon

**Comment by Rick-Anderson** [comment]
@yusufyilmazfr  thanks for the offer. See my fix in https://github.com/dotnet/AspNetCore.Docs/pull/20366

**Comment by Rick-Anderson** [comment]
@yusufyilmazfr  @JasonCard  I merged change to live https://github.com/dotnet/AspNetCore.Docs/pull/20367 so you should see the fix in 48 hours.

**Comment by JasonCard** [comment]
@yusufyilmazfr Thank you for reporting this issue.
@Rick-Anderson Thank you for the quick fix. 
FYI, I found a new bug was introduced to the no-loc feature where the terms protected by no-loc metadata (e.g. "SignalR")are displayed like ":::no-loc(SignalR):::". We're currently following up on this bug.

**Comment by yusufyilmazfr** [comment]
@Rick-Anderson thank you for your quickly response, I will check it. @JasonCard you're welcome! ^^
