### ISSUE TITLE
Sayfanın okunabilirliği düşük.

### ISSUE THREAD

**Issue by detmach** [dotnet/AspNetCore.Docs.tr-tr#20]
[Geri bildiriminizi buraya girin]
Tüm sayfa Razor yerine :::no-loc(Razor)::: yazmaktadır.

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [ASP.NET Core için Razor söz dizimi başvurusu](https://docs.microsoft.com/tr-tr/aspnet/core/mvc/views/razor?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/dotnet/AspNetCore.Docs.tr-tr/blob/live/aspnetcore/mvc/views/razor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
[Enter your feedback here] The
whole page reads ::: no-loc (Razor) ::: instead of Razor.

This is a new bug in our translation service. It was reported in  https://github.com/dotnet/AspNetCore.Docs.ru-ru/issues/102 and other places. We hope to have this fixed soon.

**Comment by Rick-Anderson** [comment]
cc @JasonCard  @scottaddie  @guardrex

**Comment by guardrex** [comment]
It's a known issue being worked on last I heard.

**Comment by JasonCard** [comment]
@detmach Thank you again for reporting this issue and it's now fixed.
cc @Rick-Anderson @scottaddie @guardrex
